### ISSUE TITLE
_cleanup can be executed too early, causing segfaults

### ISSUE THREAD

**Issue by tsee** [run4flat/C-Blocks#13]
Please accept my apologies for filing 200000 bug reports and not really contributing all the fixes. :(

Consider the following example which, while admittedly contrived, segfaults:

```
use strict; use warnings;

END { Foo->new }

use C::Blocks; use C::Blocks::PerlAPI;

package Foo;

sub new { my $c = shift; bless({@_} => $c) }
sub DESTROY {
  cblock { printf("Hello from DESTROY!\n"); }
}
```

This segfaults. The example is a bit more complicated than need be, but I'm using it in the hope that it's a bit more intuitively likely to happen than the following, simpler example:

```
use strict; use warnings;
END { foo() }

use C::Blocks; use C::Blocks::PerlAPI;

sub foo { cblock {} }
```

Perl is nice to us in that `END{}` blocks get executed in reverse order they're encountered, so under, let's say, "normal" usage, the C::Blocks END block will be executed AFTER all that are encountered by the (Perl) compiler AFTER C::Blocks is loaded. Since generally speaking, you don't have cblock{} and its siblings available before you're done loading C::Blocks, that means virtually all code is safe.

But this is once again where Perl's dynamism bites. It's perfectly legal to refer to a function before its defined. (Alternatively, we could throw in a "sub foo;" into the beginning of the second example to make that LOOK less fishy.)

I've encountered similar issues in Class::XSAccessor. There, I simply decided NOT to clean up the memory I'd allocated. In virtually any real-world Perl code, that's not a problem, but the trade-offs are that it makes other leak debugging harder, and that if somebody is seriously creating and destroying multiple perl's (not perl ithreads) in the same OS process, it's technically leaking. Not nice.

The easiest way to prevent segfaults in your case is likely to add a guard that, instead of segfaulting when a cblock is to be compiled or executed after _cleanup, croaks() with a user friendly message. All it takes to do that is to add a global (interpreter global, anyway) variable check to both the keyword plugin implementation and all custom ops (do you also generate any XSUBs? Haven't checked). Not a work of beauty, but I think still worth it for people's sanity.

If anybody every comes across this issue in a significantly sized code base, and that's really the only place you should ever accidentally run into this, he's in for a debugging session from hell...

**Comment by run4flat** [comment]
Yes, I agree it would be good to do something like this. But I wonder how far down the rabbit hole to go.

After spending some time writing and re-writing this response, here's an idea I'm starting to settle on. I could add custom `CLONE` and `DESTROY` code to `cblock` OPs. The `CLONE` code could increment a refcount for the `cblock`, and the `DESTROY` could decrement it. This would allow the machine code (and therefore function pointers) for `cblock`s to live as long as necessary, including across multiple threads. This would also clean up memory when a `cblock` is part of a string eval, even when the string eval defines a function that includes said `cblock`.

But, for `clex`, `cshare`, and `csub`, I could do what you do for Class::XSAccessor: just not clean them up. This way a `cblock` that executes during an `END` block and calls a function declared in a `cshare` would still have the functions available.

In that case, I need to learn how to really write a custom OP. Shall I study Class::XSAccessor?

**Comment by tsee** [comment]
Regarding final comment: Class::XSAccessor is doing all sorts of hairy awfulness. If that's your idea of fun, by all means! You may instead find PLua (on github) more interesting. It's very close to what you're doing - just for Lua instead of TCC.

On a related note I'm likely going to send a pull request that changes how the custom OP is installed so that it doesn't have to take the function pointer via the stack but rather embeds it into the custom OP with a trick (using the op_targ struct member).

As for custom CLONE/DESTROY hooks: How would this work? There's a sort of a hook for OP cleanup (btw: OP trees are shared between threads, so they should really only be cleaned up at the end of the program execution already anyway, I think). See the upcoming pull request for a usage example. But I don't see how you can get a CLONE hook? But I may well be missing something.

**Comment by run4flat** [comment]
I know nothing about the inner working of OP trees, which is why a `cblock` still uses `OP_RAND`. If they are shared across threads, then all I would need to add is a custom cleanup method. I would love to do so, but the documentation in perlapi and perlguts does not seem to go into these details.

**Comment by run4flat** [comment]
YES, everything here is wonderful: https://github.com/tsee/p5-Plua/blob/master/plu_global_state.c#L23

**Comment by tsee** [comment]
Re PLua, plu_op.c is relevant, too.

Anyway, pull request about to land.

**Comment by tsee** [comment]
https://github.com/run4flat/C-Blocks/pull/14

**Comment by tsee** [comment]
Actually, re-reading the Plua code you referenced:

```
/* Register super-late global cleanup hook for global state */
  Perl_call_atexit(aTHX_ plu_global_state_final_cleanup, NULL);
```

That might be the solution to the original issue in this ticket. Man, I WROTE THAT CODE BUT I DIDN'T REMEMBER! m(

Perl_call_atexit happens after all normal Perl code is done running. It should be good enough for this purpose (though I'd try to test it carefully...).

**Comment by tsee** [comment]
Proposed change implemented with https://github.com/run4flat/C-Blocks/pull/15

That should take care of this entire issue, so I'm closing this.
